---
name: Himal
surname: Shrestha
position: "PhD Student"
address: "La Trobe University"
www: "xx.github.io"
email: "shta.himal2007@gmail.com"
github: himal2007
linkedin: himal-shrestha
orcid: 0000-0002-4470-4830
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
aboutme: "I am a PhD student in Bioinformatics at La Trobe University studying the transmission of infectious diseases. I utilize different computational and mathematical approaches to integrate genomic, environmental and epidemiological data to predict, prevent and eliminate diseases. I am equally adept at different molecular and laboratory techniques."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = year,
    where = where
  )

```

# Skills
```{r SKILLS}
skills %>%
  detailed_entries(
    what = area,
    why = skills
  )
```

# Research experience
```{r RESEARCH}
research %>%
  detailed_entries(
    with = Position,
    what = inst,
    why = detail,
    when = year,
    where = where
  )
```

# Teaching experience
```{r TEACHING}
teaching %>%
  detailed_entries(
    with = Position,
    what = inst,
    why = detail,
    when = year,
    where = where
  )
```

# Awards
```{r AWARDS}
awards %>%
  detailed_entries(
    with = award,
    what = inst,
    when = year,
    where = where
  )
```

# Trainings and workshops attended
```{r TRAININGS}
trainings %>%
  detailed_entries(
    what = type,
    why = training
  )
```

# Publications

```{r PUBLICATIONS-2}
publications %>%
  detailed_entries(
    what = type,
    why = name
  )
```

# Volunteering experience
```{r VOLUNTEERING}
voluteering %>% detailed_entries(
  what = task,
  why = details
)
```

# Publications

```{r PUBLICATIONS}
scholar::get_publications("wx-hSU4AAAAJ") %>% 
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal
  )
```

