---
name: Himal
surname: Shrestha
position: "PhD Student"
address: "La Trobe University"
www: "himal2007.netlify.app"
email: "H.Shrestha@latrobe.edu.au"
github: himal2007
linkedin: himal-shrestha
orcid: 0000-0002-4470-4830
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
keep_tex: true
aboutme: "As a PhD graduate in Bioinformatics with expertise in computational and mathematical modelling, I am passionate about using data to predict, prevent, and eliminate diseases. My research at La Trobe University involved studying the transmission of parasitic disease, 'River Blindness', by integrating genomic, environmental, and epidemiological data with a variety of modelling and analytical approaches. I am now seeking new opportunities that will enable me to utilise and expand my current skill sets."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
             ,'commonmark'
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = year,
    where = where,
    .protect = FALSE
  )

```

# Skills
```{r SKILLS}
skills %>%
  detailed_entries(
    what = area,
    why = skills,
    .protect = FALSE
  )
```

# Employment
```{r EMPLOYMENT, eval = TRUE}
employment %>%
  detailed_entries(
    with = Position,
    what = inst,
    why = detail,
    when = year,
    where = where,
    .protect = FALSE
  )
```
# Awards
```{r AWARDS}
awards %>%
  detailed_entries(
    with = award,
    what = inst,
    when = year,
    where = where,
    .protect = TRUE
  )
```

# Research grants
```{r GRANTS, eval = TRUE}
grants %>%
  detailed_entries(
    with = grant,
    what = inst,
    why = detail,
    when = year,
    where = where,
    .protect = TRUE
  )
```
\pagebreak
# Publications

```{r PUBLICATIONS-2, eval=TRUE}
publication %>%
  detailed_entries(
    what = type,
    why = name,
    .protect = FALSE
  )
```


```{r RESEARCH, eval = FALSE}
# Research experience
# Kept for future purposes - now replaced by Employment
research %>%
  detailed_entries(
    with = Position,
    what = inst,
    why = detail,
    when = year,
    where = where,
    .protect = FALSE
  )
```

```{r TEACHING, eval = FALSE}
# Teaching experience
# Kept for future purposes - now replaced by Employment
teaching %>%
  detailed_entries(
    with = Position,
    what = inst,
    why = detail,
    when = year,
    where = where,
    .protect = FALSE
  )
```

# Volunteering experience
```{r VOLUNTEERING}
voluteering %>% detailed_entries(
  what = task,
  why = details,
  .protect = FALSE
)
```

# Trainings and workshops attended
```{r TRAININGS, eval = TRUE}
trainings %>%
  detailed_entries(
    what = type,
    why = training,
    .protect = FALSE
  )
```